version: '{build}'
image: Visual Studio 2017
platform:
- x86
- x64
environment:
  matrix:
  - PYTHON: 27
  - PYTHON: 36
install:
- ps: |
    git submodule update -q --init --recursive
    if ($env:PLATFORM -eq "x64") { $env:PYTHON = "$env:PYTHON-x64" }
    $env:PATH = "C:\Python$env:PYTHON\;C:\Python$env:PYTHON\Scripts\;$env:PATH"
    pip install --disable-pip-version-check --user --upgrade pip setuptools
build_script:
- ps: |
    python setup.py bdist_wheel
    pip install --verbose dist\*.whl
